version: '3.8'

services:
  gateway:
    build:
       context: .
       dockerfile: KeycloakGateway/Dockerfile
    container_name: gateway
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Kafka__BootstrapServers: <your-server-ip>:9092
      Kafka__Topic: email-topic
    networks:
      - gateway-net

networks:
  gateway-net:
    driver: bridge
